### ISSUE TITLE
Discussion about the semantics of 'while'

### ISSUE THREAD

**Issue by shalabhc** [aardappel/lobster#23]
(Not sure if this is the appropriate forum for discussion but I didn't find a mailing list.)

I wanted to discuss the special evaluation semantics of expressions passed to `while` in the language. This actually confused me for a bit until I made my way to the end of the language reference (https://htmlpreview.github.io/?https://raw.githubusercontent.com/aardappel/lobster/master/lobster/docs/language_reference.html#built-in-functions). Before that I was looking for a way to pass unevaluated expressions around, but now I understand only calling `while` can pass an unevaluated expression (perhaps wrapping it in an anonymous function?) while *all* other calls pass the evaluated value.

Specifically, in the following code `expr` is passed unevaluated to `while`, but `expr2` and `expr3` are immediately evaluated and the value is then passed to the respective function:

```python
while expr:
   body

if expr2:
  body

for(expr3):
  body
```

From a design point of view, special casing `while` sticks out a bit. It breaks the expectation that expressions are evaluated immediately, but it does offer the convenient syntax. However it can still be confusing, e.g. I'm not sure how to pass an expression when calling while with the `while(...)` syntax, as opposed to the `while ...: ...` syntax.

I have a couple of questions:

1. Is there a way to define a function that accepts an unevaluated expression (i.e. can I implement `while` in lobster?) 
2. Are there an plans or ideas to 'sort out' the above exception around `while`?

I'm thinking if we have (1) above, then maybe `while` would not look like an outlier. OTOH, it means we would always have to look at the definition to know the call semantics.

**Comment by aardappel** [comment]
This is totally appropriate place for discussion, thanks for the feedback!

The funny thing is that most programming languages (C/Java/Python..) have an exception for `while`: they all get an unevaluated expression, and it is the only expression to have this property (well, in C there's also `for` of course). To have more uniform syntax, `while` in C should read something like: `while { a < 10 } { a++; }` since C uses `{}` for unevaluated things. In Python, the condition should be a block also.

In Lobster it is actually less special case than you think, since that expression is actually represented in the compiler as a argument-less lambda, and treated as such during type checking and code generation. If the parser had a way for user defined functions to request this kind of parsing (e.g. a type `:exp`) then that would work without further changes to the language.

To currently write your own `while`:

    def mywhile(cond, do):
        while cond(): body()

    mywhile():
        a < 10:
    do:
        a++

That would be what non-special case in Lobster looks like. If I'd allow `def mywhile(cond:exp, do)` as a hint to the parser, it could look just like the built-in one.

I feel that `while` special casing is a wart on any language design, at the same time it is a frequent-ly enough used construct that it can't look alien like `mywhile` does. Do I want to enable this kind of syntax for all functions? I think I'd prefer not, since it is confusing: I like that you can syntactically see what is going to be evaluated when, and Lobster's lambda syntax is terse enough as it is (just a single `:` in the cases above). I also don't think that functions that receive 2 lambdas is a frequent enough thing that it warrents "optimizing" the syntax of something like `mywhile` for. But I could be persuaded. What do you think?

**Comment by shalabhc** [comment]
I understand that internally the `while` is very consistent in that it is just a normal function that accepts two functions. What I want to talk about the user experience and mental model.

I agree that `while` is special cased in Python etc. but I don't think it's a wart and it doesn't stick out as much because even `if`, `for` etc are 'special cased'. They're all keywords with special syntax and evaluation semantics. Consider you can't use the `for x in y` construct in any other form (e.g. function call style) and that `x in y` means something very different by itself. Some keywords introduce new locals (`for`, `except`) while others remove them (`del`). A keyword has the power (in my mind) to define its syntax and semantics. C/Java do this for not just `while` but also `for` as you point out (and `do/while`).

In terms of expectation, when I find a keyword, I *know* it could be doing absolutely anything in terms of when it evaluates expressions and how many times. I'd reach for the language reference to be sure. By contrast when I encounter a function call or an expression, I know exactly what will be evaluated when. The stdlib functions don't get any more power here than user defined functions.

Lobster seems more minimal wrt keywords (which is harder, and really great!) and remarkably demotes many control structures into stdlib function calls. Except for this one thing - `while` - that gets special evaluation power at the syntax level. This breaks the expectation and principle of least surprise. There is now a single hole in the consistency, which leads to thoughts like: could any stdlib function, now or in the future, develop this special power to accept unevaluated expressions? How can I be sure? Does this mean I should treat all stdlib functions as keywords in other languages?

This goes into the question of whether the stdlib should have special language powers - I think it should not. Golang does this with generics and it feels like the designers are saying 'yes this feature is good/powerful but we don't trust *you* with using this wisely, however we will'. So I'm arguing the users should be given the same power (syntax/semantics wise) that the stdlib has.

I don't really have a great solution. One option is to label `while` as a keyword, but it feels it should be in the same bucket as `if`, `for` etc. Another option is remove the auto-wrapped expression and force people to write some other syntax such as:

```python
while :condition:
  body
```

Slightly clunky but more consistent, and potentially also more error prone if you forget the leading `:`. 

Another direction is to let any function declare that it accepts unevaluated expressions (i.e. it accepts a function and the language auto-wraps expressions to make them functions). I think this is the one I like most - let everyone have the same, deep, power. The important thing here is that any reader should be able to easily see which functions are special like this. Doing this while keeping the code look clean is the tricky part.

**Comment by aardappel** [comment]
You have a good point: it is a bigger wart in Lobster because the rest of Lobster is more elegant / regular / minimalistic than comparable languages.

While requiring people to write an extra `:` in `while` would be the most elegant solution, I also want to have a syntax that appeals to people's expectations coming from similar languages. Also, unless I made provisions for leaving out `()` in certain circumstances, in the current language it would have to be:

    while(): cond:
        body

or even worse:

    while():
        cond
    do:
        body

Making it possible to omit all those things just for the sake of reducing `while` to its expected syntax may be going a bit far.

So in that sense, generalizing "here a naked single expression is actually a no-argument lambda if the function explicitly request it" is the better option, I think.

Should be simple to add, as it is just a parser change. I could give that a go if you feel like experimenting with it.

**Comment by shalabhc** [comment]
Sure, sounds good!

I still think to do it right it must be obvious (or quick and easy) for the reader to distinguish the functions where the expressions are auto wrapped in the lambda.

**Comment by aardappel** [comment]
I agree that be ideal, but I don't know how to do that without making `while` look unfamiliar.

I'll see if I can add it over the weekend.

**Comment by shalabhc** [comment]
Yeah I agree it's not desirable to have `while` to look unfamiliar. The question is how easy it is for a reader to determine the evaluation semantics of some arbitrary code they are looking at - ordered here based on effort:

- The call site syntax is different. Easy to spot, no context switch required, but makes it unfamiliar - so out.
- Look elsewhere in the same file to see if it's a special construct. Not super easy but doesn't require context switch out of the file.
  - At some point I had an idea of using specialized import statements, e.g. `keyword otherwhile from othermodule` somewhere on the top of the file.
- Dig around to find the definition to see if its special.
  - `keyword otherwhile(...)` - different defintion syntax
  - `def otherwhile(x:expr)` - special type

Perhaps worthwhile exploring similar alternatives at some point?

**Comment by gwvo** [comment]
As I said, the total amount of changes to support this feature are absolutely minimal, see here (with example): https://github.com/aardappel/lobster/commit/d1cc90f9ee81640bbf7777c703241c4383082d22

I made the type annotation "obnoxious" so it is easy to spot, though no call-site annotation yet. I am starting to think it may not be as big a deal, especially if the name of the function has the word `while` in it :) This should be an infrequently used feature I'd think.

**Comment by shalabhc** [comment]
Sweet, works well.

```python
def twice(e: lazy_expression):
  e()
  e()

var a = 4
twice a = a + 1
print a   // --> 6
```

**Comment by aardappel** [comment]
Hah, that's a nice use of it :)

**Comment by Asmageddon** [comment]
This is really cool, how is it handled internally? I'm thinking of having something similar in my language as well, for the sake of doing cool macros. I'd like to make it so the only unevaluated code is what's in {} blocks, but hmmm... well, idk, that's not a project I'm gonna get started on anytime soon, anyway.

**Comment by aardappel** [comment]
@Asmageddon Lobster generally already has a very terse syntax for closures, so this is just the tersest possible closure syntax, that was already implemented for `while`. When it sees an arg of type `lazy_expression` it ends up calling `ParseFunction` for the following expression, and expects no arguments, no `()`, just a single expression body. The resulting code is just as if you had written `twice(def (): a= a + 1)`.

Similarly, for more regular closure arguments, it parses a call like `f(1) a: a + 1` as if you had written `f(1, def (a): a + 1)`

**Comment by Asmageddon** [comment]
What I am thinking of for my language, is to have a set of "core macros", stuff like arithmetic, syscalls, memory allocations, calling and exiting a function/closure, etc.

For function application, the syntax I am thinking of is simply `A B`, e.g. `f(1,2,3)` is essentially `f((1,2,3))`, but you can also do `f"hello"`, `f a`, or `f 20`, or in special-case syntax for numbers, `20f`.

After that, all {} blocks are code, stored as AST and interactive, though of course to execute them, they have to be compiled - beforehand when applicable, at runtime when not - but they are not closures, and in fact have no connection to their outer scope - linking scopes and otherwise defining their meaning is something for a macro to do. A macro such as `do`, `for`, `while`, `fn`, `match`, and so on, and the way they will achieve it is by calling mentioned built-in "core macros".

Even my type system is not hardcoded, but is instead replaced with a "constraint operator", `:`, which applies any arbitrary constraint - be it static typing, something like `a: Int: Assert{a != 0}`, or metric units, essentially making it possible to extend or even replace the type system itself in a very fundamental way.

I'm still not sure about some of the specifics of that system, however, and as it seems likely that I will die before/instead of ever becoming functional enough to achieve anything, they will likely never be worked out. For all of probability, this will be the only place I ever record my thoughts :-(

Anyway, the specifics that have not been worked out namely are: How does memory allocation follow from and play with this kind of typing, whether inference would be feasible, if it should apply to just variables(and what even *are* variables, in this context, then?) or to values also?

Also, perhaps most importantly, how do you even make a system like this work with unevaluated expressions? If for me, `=` is just another operator, and macros can easily replace it, what exactly are the semantics of `=(a: Int, 5)`?? Would having a macro that makes it possible to read the identity of a variable instead of its content, e.g. symbol "a" in scope "0x1234", with constraints such and such applied, be enough?

-----

Anyway, sorry for kinda hijacking an issue on your project with this stuff.

Truth is, @aardappel, I have had this repository on follow, hoping to one day reach out to you, because I thought that making a language like Lobster as you are is really cool, and have since found that you've also worked on Cube 2 - a project I really admire(d?), but kinda never really said anything, since well, not much good can really come of it, eh.

**Comment by aardappel** [comment]
@Asmageddon : a language where all the higher level features are built with macros on top of primitives is certainly appealing. Lobster uses it flexible function syntax to try to achieve something similar, but it is of course limited compared to macros. Making it figure out even scoping sounds challenging.. you're essentially implementing half the compiler in your macros.

programmable constraints sounds very much like "dependent typing", which is very complicated to get right.

I know @paniq (Leonard Ritter) is working on such a language I seem to remember, but can't find it right now..

**Comment by Asmageddon** [comment]
@aardappel For scopes I am thinking of something like what can be done in Lua with using the `__index` metamethod to tag a parent scope onto a "sandbox" environment, just more robust, e.g. a `Scope` object would be one of the built-in "primitives"(or at least special-ish case objects), just as I would need similar primitives to represent functions, types, etc.

Although, of course, I would be foolish to think that such a system would have anything but a more than fair share of headaches :D

> programmable constraints sounds very much like "dependent typing", which is very complicated to get right.

And yeah, it is pretty much dependent typing on steroids... although for starters, I can keep the constraints as runtime checks, just leaving the underlying compiler(LLVM?) to figure what it can out, leaving the primary challenge being to implement a non-hardcoded type system. It's likely to be simpler than dependent typing, but... it's still daunting.

> And as for Cube 2.. small world eh? :)

Haha yeah, I've been looking at various stuff recently, and I thought "Hmm, where have I seen this name..". Still, it was a really cool project. Are you by chance involved in Tesseract as well? I've not looked too closely into it, and it's a real shame that the engine seems to have never been used anywhere, because its featureset looked extremely impressive.

**Comment by Asmageddon** [comment]
@aardappel My intention is a statically typed language, with focus on having primarily only zero-cost abstractions, and an extremely rich macro system, and very generic syntax that is conductive to writing DSLs, and otherwise extending the language.

I think LLVM would handle it alright, the difficulty would be in figuring out how to translate the constraint system into C-like code into LLVM IR, and in general the semantics of it. I'd definitively need some objects to represent the low level concept of basic types and their storage... perhaps type constraints would need to be bootstraped a bit on top of those primitives, rather than purely higher level to do that, though.

Well, that's all thinking for another day.

And yeah, I don't think there are many people who know about Tesseract. It never really seemed like something casually approachable to make a game on top of. In a way, you could call it weirder that so many things were made on top of Cube 2.

**Comment by shalabhc** [comment]
If you're experimenting with building a statically typed language, terralang.org might be of interest. It is kind of like a powerful Lua based metaprogramming system on top of LLVM.

**Comment by Asmageddon** [comment]
@shalabhc Oh yes, I know about Terra, it's an amazing concept and I kinda really wish that it took off.

**Comment by aardappel** [comment]
Fun discussion, but closing :)
