### ISSUE TITLE
Fatal application exit when calling function of inherited class

### ISSUE THREAD

**Issue by ValetNoir** [aardappel/lobster#257]
Hey ! I was trying to have a parent class contain an empty draw function, so I could overwrite it **with an argument** (else I couldn't, it would give me a weird `error: 'de-indentation' expected, found 'indentation'`) in the child classes (not really useful when I think about it 🤔) and I got the "send this to the developper window".

Here is a repro case:
```lobster
class Foo:
    def foo() -> void

class FooFoo: Foo
    // trying to overwrite the function
    def foo(text: string):
        print(text)

let a = Foo {}
a.foo()

// same with child class
// let a = FooFoo {}
// a.foo() // <- forget to pass an argument, calls the wrong version of the function
```
and the log: [lobster.exe.exp.log](https://github.com/aardappel/lobster/files/12319623/lobster.exe.exp.log)

Thanks for taking a look 😁 !

**Comment by aardappel** [comment]
Fixed in https://github.com/aardappel/lobster/commit/b53ef6ac7fb8a54cdc473adfb0ba8837df7e586e

`def foo() -> void` indeed declares a function type. The error was that it allowed a function type and a regular function to share the same name, and then when calling it, it didn't notice it was calling a type because there was also a regular function version. All of that is now disallowed :)

**Comment by ValetNoir** [comment]
Thanks a lot for the advices and for the fix !
