### ISSUE TITLE
OSX build instructions currently fail

### ISSUE THREAD

**Issue by jasper-lyons** [aardappel/lobster#268]
CMake can't find a compiler and this causes the build to error out.

I had a successful play with simply using cmake over [here](https://github.com/jasper-lyons/lobster). The examples I tested all work. Let me know if you'd accept a PR with the documentation changes I added.

**Comment by aardappel** [comment]
And why can't CMake find a compiler if you have clang installed? Something different about your setup?

The existing instructions work on CI and also tested them manually on an M1.

**Comment by jasper-lyons** [comment]
Because the `CXX` environment variable wasn't set. I'm unaware of your setup so can't tell you what might be different.

I think they work in CI as the CI scripts export a `CXX` env variable.

Also, I found that the `-G Xcode` option also caused cmake to bail. By removing it I was able to get cmake to run and then compile lobster.

**Comment by aardappel** [comment]
We want to build with Xcode though. It's the default toolchain on MacOS, and people might want to, you know, debug or use the IDE. I bet Xcode does not need that variable because it itself installs the toolchain.

I believer after installing Xcode, there is a separate step where it asks you to install the toolchain, did you go thru that? Is the Clang you have from Xcode, or installed in a different way?

**Comment by jasper-lyons** [comment]
Ah, reinstalling Xcode seems to fix the original build script. I'm not sure why though :(.
