### ISSUE TITLE
Using construct to avoid prefixes

### ISSUE THREAD

**Issue by jacereda** [aardappel/lobster#34]
What's your stance on something like this?

```
using gui:
      setclickcolors(color_dark_green, color_green)
      start(gl_window_size(), 1, 1, true):
        hblock(1, 0):
        
      ...
```

**Comment by aardappel** [comment]
It would be pretty easy to add.. though personally not sure how useful I'd find it. I chose to do namespacing with `_` exactly because it would feel very "integrated" with the name, such that it would be ok to have the namespace there always.

I find other languages where sometimes the namespace is present and sometimes not making code generally harder to parse. I agree that with case like constructing a `gui` the namespace use can get repetitive, but when mixing things from different namespaces it is helpful to keep it.

**Comment by jacereda** [comment]
And I guess explicit full names might be easier for things like editor tools.
