### ISSUE TITLE
Feature Request: Adding range support to for and vectors

### ISSUE THREAD

**Issue by davidbruce** [aardappel/lobster#51]
Currently ranges are only used in switch statements.  What are your thoughts on adding them to loops and vectors:

```
let x = [4..10]
//Giving us a vector of [4,5,6,7,8,9,10]

for 4..6: print(_)
//result:
//4
//5
//6
```

Currently I am using this for ranges:
```
//not inclusive
def range(start, end, func):
    let r = []
    while start < end:
        r.push(start)
        start = func(start) 
    return r

def range(start, end):
    return range(start,end): _ + 1
```

It works, but language level support would be nice.
I can take a look at this if you support this feature.

**Comment by aardappel** [comment]
Adding them to vector constructors would indeed by nice, and wouldn't be very hard to do. Currently I use `map` to generate ranges, e.g. `map(6): _ + 4`.

`for` currently has no special syntax compared to other function calls, so making it understand ranges like that may be a bit special purpose, it be better to just piggy-back on constructors, e.g. `for [4..6]: print(_)` (which of course is less efficient). Current alternatives: `for 3: print(_ + 4)` or `for_range(4, 6): print(_)` (from std.lobster).

Come to think of it, one thing I wouldn't like about a notation like `4..10` is that the default interpretation is inclusive, where-as exclusive ranges are much more correct for a 0-based language :)

**Comment by davidbruce** [comment]
I'm also currently using `map`, but pine away for `[..]`. 
I also agree about exclusive ranges and would welcome the change if you made it across the board.    What are your thoughts on a decrementing range: 10..4: [10,9,8,7,6,5]?

I could live without the `for [4..6]`.

**Comment by aardappel** [comment]
Exclusive would be better, but I think it would confuse users, given that many languages have similar syntax that is inclusive. In fact, Lobster's own `switch` is inclusive.

Given that, I am not sure it warrants its own syntax. Not sure about you, but 99% of the time I want a range, it starts at 0, in which case `map` is great. Maybe we should add a `map_range` much like we have a `for_range` ?

**Comment by davidbruce** [comment]
After looking at quite a few other languages (Groovy, Kotlin, Elixir, F#, etc) it appears that regardless of them being 0 index `..` is still inclusive.  I would prefer this over going the map_range route, just because it seems natural since the syntax already exists in a switch.  

It looks like we'd need to implement it here? https://github.com/aardappel/lobster/blob/a7ba34d623a548be0132aa59a1e8dbabe48a589f/dev/src/lobster/parser.h#L1069

If you are against this though, I can implement the map_range instead.

**Comment by aardappel** [comment]
It's not like the syntax "already exists", since it would need its own node, its own type checking and code generation. The only that can be reused is the token :)

I vote for just a `map_range` function in `std.lobster`. Making it inclusive will be confusing with other languages and not as useful, but making it exclusive will make it mean something different from `switch`. You can't win. For such a minor feature, a function is better.

**Comment by davidbruce** [comment]
Alright I concede on the `..` syntax.  :)

I personally like`range` more than `map_range`, but I can change it if you want it to be `map_range`.  

Also by using lazy_expression we can make it a bit more flexible.  What do you think of the following:
```
import std

def range(start, end, cond:lazy_expression, fun):
    let r = vector_reserve(typeof return, end)
    if ((start < end && start == 0  && fun(start) == 0)
    or (start > end && end == 0 && fun(end) == 0 && cond(0,0))):
        fatal_exit("infinite loop detected")
    while cond(start, end):
        r.push(start)
        start = fun(start)
    return r

def range(start, end, fun):
    if (start < end):
        return range(start, end, _x < _y, fun)
    else:
        return range(start, end, _x > _y, fun)

def range(start, end):
    if (start < end):
        return range(start, end): _ + 1
    else:
        return range(start, end): _ - 1

print("range(0, 10):\n" + range(0, 10))
print("\nrange(10,0):\n" + range(10, 0))
print("\nrange(0,100): _ + 2\n" + range(0, 100): _ + 2)
print("\nrange(100, 0): _ - 2:\n" + range(100, 0): _ - 2)
print("\nrange(1, 100): _ * 2:\n" + range(1, 100): _ * 2)
print("\nrange(100, 0): _ / 2:\n" + range(100, 0): _ / 2)
print("\nrange(0, 10, _x <= _y): _ + 1:\n" + range(0, 10, _x <= _y): _ + 1)
print("\nrange(0, 100, _x <= _y): _ + 10:\n" + range(0, 100, _x <= _y): _ + 10)
print("\nrange(10, 0, _x >= _y): _ -1:\n" + range(10, 0, _x >= _y): _ -1)
print("\nrange(100, 0, _x >= _y): _ -10:\n" + range(100, 0, _x >= _y): _ -10)
print("\nrange(1, 128, _x <= _y): _ * 2:\n" + range(1, 128, _x <= _y): _ * 2)
print("\nrange(128, 1, _x >= _y): _ / 2:\n" + range(128, 1, _x >= _y): _ / 2)
```
Output:
```
range(0, 10):
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

range(10,0):
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

range(0,100): _ + 2
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]

range(100, 0): _ - 2:
[100, 98, 96, 94, 92, 90, 88, 86, 84, 82, 80, 78, 76, 74, 72, 70, 68, 66, 64, 62, 60, 58, 56, 54, 52, 50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2]

range(1, 100): _ * 2:
[1, 2, 4, 8, 16, 32, 64]

range(100, 0): _ / 2:
[100, 50, 25, 12, 6, 3, 1]

range(0, 10, _x <= _y): _ + 1:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

range(0, 100, _x <= _y): _ + 10:
[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

range(10, 0, _x >= _y): _ -1:
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

range(100, 0, _x >= _y): _ -10:
[100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 0]

range(1, 128, _x <= _y): _ * 2:
[1, 2, 4, 8, 16, 32, 64, 128]

range(128, 1, _x >= _y): _ / 2:
[128, 64, 32, 16, 8, 4, 2, 1]
```

**Comment by aardappel** [comment]
Sorry, going to have to be picky again :)

- Not a fan of "kitchen sink" functions that have a lot of possible ways they can work, guarded by conditionals. For `std` functions, better to have ones that do one thing, and one thing well, without conditions. That makes them fast and predictable.
- Similarly, would want to avoid any runtime errors in base functions like that.
- `lazy_expression` is there to avoid `while` having to become a special case, but I am really not a fan of it. Using it in other contexts really leads to unexpected behavior, especially here where you are using it to create a lambda that takes arguments, whereas all use of it so far has been for argument-less function (as in `while`). In fact, I didn't even know this worked :)
- The behavior of `range(0,100): _ + 2` is very surprising, since I would expect that to result in `[2, 3, 4, ..]` like almost all existing higher order functions. I'd suggest making step a regular argument.
- You're adding the functionality of `filter` and `map` in a single function. I personally like to keep these separate, so I can compose them in whatever way is needed.

I'd suggest just `map_range(base, iters, fun)` , `map_range(base, iters, step, fun)` (the latter can also go in reverse).

That said, we don't need to agree on this. People should really have their own tool-box with favorite function if need be :)

**Comment by davidbruce** [comment]
Being picky is absolutely fine. :)

I'm just glad you're responding thoroughly as it will help me become a better contributer. 

I'll take a stab at map_range tomorrow.
