### ISSUE TITLE
Feature request: sample of rendering a textured mesh

### ISSUE THREAD

**Issue by kriskowal** [aardappel/lobster#68]
One exercise I’d like to do while learning Lingua de Lagosta is to render a cube with a die face on each side. I could use a hint, especially considering how I stumbled through rendering a texture on a unit square.

I’d be glad to submit the sample, but could use a push here.

**Comment by aardappel** [comment]
that's actually non-trivial, since either you render each face seperately (since they have a separate texture), or you have a texture that contains all 6 die faces in one, and then you can apply that to a cube mesh with appropriate texture coordinates.

So rendering a cube with a single texture might be a more basic example.

Even so, just generating a mesh for a cube is a bit of work (see `lobstercraft.lobster`), so I wonder if adding a `gl_cube` built-in might be better? Then again, generating meshes is not performance sensitive, so maybe better done in Lobster.

**Comment by kriskowal** [comment]
I don’t suppose it’s possible to billboard with gl_rect in a 3D context. I’d be satisfied with 6 billboards.

I’d be interested in trying each of these different ideas. I could certainly attempt to make a cube mesh texture.

My understanding of the prior art to lobstercraft is that the engine creates consolidated meshes for aggregate surfaces for chunks of the world. I’m not itching to go that far with this direction, but someone might come along and carry that forward.

It would be neat to project a 2D worlds on the faces of a 3D cube though. That would be directly applicable for the project I have in mind. Would it be silly to generate a mesh texture on the fly?

**Comment by aardappel** [comment]
yeah `gl_rect` can't take a 3D orientation, or you'd need to wrap it in complex `gl_rotate` / `gl_translate` which would be inefficient and clumsy.

If it has to be face based, I'd start from what is in `lobstercraft.lobster`

**Comment by aardappel** [comment]
We now have `samples/image.lobster` and various others that do texture rendering.
