### ISSUE TITLE
Can't compile against wayland

### ISSUE THREAD

**Issue by tekknolagi** [aardappel/lobster#77]
Is there a way to avoid compiling against wayland? I run into issues when building:

```
[ 44%] Building C object external/SDL/CMakeFiles/SDL2-static.dir/src/video/wayland/SDL_waylandmouse.c.o
/home/max/Documents/Dev/lobster/dev/external/SDL/src/video/wayland/SDL_waylandevents.c:41:10: fatal error: pointer-constraints-unstable-v1-client-protocol.h: No such file or directory
 #include "pointer-constraints-unstable-v1-client-protocol.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

```
willow% lsb_release -irc
Distributor ID:	Ubuntu
Release:	18.04
Codename:	bionic
willow% 
```

Revision 314f6c690b364c3dee850a41e8425f9cd80b76c9

**Comment by tekknolagi** [comment]
Hm, this file looks like it is in your repo. Maybe something is wrong with the include path?

**Comment by aardappel** [comment]
Fixed: https://github.com/aardappel/lobster/commit/2ae85d157296dd5cb1d9f346bfdf4f5e29f18475

`SDL_waylandmouse.c` is in the repo since it simply contains all SDL sourcefiles, so what changed recently is something in how it detects wether it should build Wayland support. Anyway, I turned it explictly off, and now it builds and runs fine.

**Comment by aardappel** [comment]
Weird, that previous commit missed the `OFF` yet it still worked. New version here: https://github.com/aardappel/lobster/commit/317cc2133065473e4c9a6d5eb03d34def4490b93
