### ISSUE TITLE
Computed Textures Fade As They Downsample (unless mimap gen is disabled)

### ISSUE THREAD

**Issue by jcorbin** [aardappel/lobster#81]
Using [demo texscal.lobster](https://gist.github.com/jcorbin/cab8aa3f369dd08a373330f1617dd547), which:
- draws a colorful test pattern into a texture
- then draws that texture on a unit square
- over a colored white square to make the alpha fade mare apparent (vs the global black background)

So you start out with:
![image](https://user-images.githubusercontent.com/49715/69571805-b034da00-0f77-11ea-9055-22efad8f5981.png)

But dragging that slider gives:
![image](https://user-images.githubusercontent.com/49715/69571817-b6c35180-0f77-11ea-8b6c-a85fee321871.png)

Eventually going full transparent about half way through:
![image](https://user-images.githubusercontent.com/49715/69571794-aa3ef900-0f77-11ea-86bd-74a4caf06be9.png)

Enabling the `texture_format_nomimap` eliminates the alpha fade out.

**Comment by aardappel** [comment]
Actually, the problem here is specific to rendering to texture: it uses mip-0 as a framebuffer, and the rest remains un-initialized (white). We'd need to add a `gl_update_mipmaps` to call at the end of rendering to texture to use this properly with scaling. But you wouldn't always want to call it, since generating mipmaps is somewhat expensive. Or maybe it could be automatic if `texture_format_nomipmap` is not specified.

Note, most functions in `util3d.lobster` force `texture_format_nomipmap` for that reason, but you have your own version.

All my use-cases of render to texture so far have been with textures that got re-rendered at the same size :)
