### ISSUE TITLE
is lobster production-mature ?

### ISSUE THREAD

**Issue by codenoid** [aardappel/lobster#92]

**Comment by aardappel** [comment]
Lobster has been in development since 2011, and has seen a ton of game prototypes made in it, so in that sense it is a relatively stable code base.

At the same time, big changes still keep happening, most recently the explicit type parameters and compile time reference counting. These changes changed a lot of how the type system functions, so regressions are possible.

I expect invasive changes to happen less and less, but the language is not necessarily finished or set in stone either.

Does that mean it is production ready? I don't know, depends what you would use it for. If you use it for something serious and a future change breaks, I'd be happy to help find the problem :) You can always pin to a particular version and only upgrade if it works for you.
