### ISSUE TITLE
Dynamic Scope Footgun

### ISSUE THREAD

**Issue by jcorbin** [aardappel/lobster#93]
Once one gets into the groove of writing lobster, writing contextual state management routines is a seemingly "obvious" or "natural" thing to do (e.g. builtins like `gl_translate` already point in this direction.

However when you compose this with lobster's `return` semantics, you can easily get surprising leaks.

```
var state = 0

def with_some_state(x, body):
    let old_state = state
    state = x
    body()
    state = old_state

def foo():
    print("a:"+state)
    with_some_state(42):
        print("b:"+state)
        return 99      // NOTE causes a leak because it skips the teardown phase of with_some_state
    print("c:"+state)

print("d:"+state)
with_some_state(99):
    print("e:"+state)
    let result = foo()
    print("f:"+state)
print("g:"+state)
```

Prints:
```
d:0
e:99
a:99
b:42
f:42      <-- XXX state from foo() leaked out into somewhere_else()
g:0
```

I'm not at all sure what to do about this, but wanted to at least start a conversation about this gotcha.

Basically the tension comes when:
- you need to return a value
- ... from within an inner scope of a function
- ... but you didn't particularly care about the actual control flow semantics of that `return` entailed

Some awkward workarounds:

1. the "return around" approach:
```
def foo():
    var ret_val = 99
    with_some_state(42):
        ret_val = 99
    return ret_val
```

2. the "return through" approach:
```
def with_some_state(x, body):
    let old_state = state
    state = x
    let ret_val = body()
    state = old_state
    return ret_val

def foo():
    with_some_state(42):
        99
```

Some adjacent linguistic shibboleths:
- named return slots, would be aligned with the "return around" workaround, but without the manual setup noise
- support for a stack of teardown functions to run when unwinding would allow for more reliable mutators, but cuts directly against the grain of lobster's simple/power/unique return semantics
- if anonymous functions (bodies, blocks, whatever) counted as a return point, than this code would just work, and the surprise leak would go away; named return could still choose to `return from foo` if you really meant to skip out on your stack

**Comment by aardappel** [comment]
Yup, this is to some extend a known issue, but should probably at least be better documented. Mentioned here in the TODO.txt: https://github.com/aardappel/lobster/blob/da09a2c36dfe4ce45699e53ce5f032cbefaf18ea/dev/TODO.txt#L208-L228

I am thinking that at this stage, this problem is not important enough to warrant a fix, given that "proper" fixes would be an expensive language feature. You need to be able to run code on teardown, which would mean "destructors", registering a function like you say, or probably best fitting for Lobster would be Zig's [defer](https://ziglang.org/documentation/master/#defer) feature.

These features are not simple because you need to be doing regular code execution in the context of unwinding possibly multiple stack frames, so once you hit the end of such a function, you need to go back to, oh yeah, I was unwinding. Or the regular code execution causes another unwind and things get complicated.

Currently, yes, you're either not supposed to have global side effects at the end of higher order functions, or assume that `return` is only used in exceptional situations and be ok with the inconsistent state when it happens. That is not ideal, but if it makes the language a ton simpler, it may be ok?

`return` is definitely meant to default to returning from named functions, returning from just the lambda would be weird (and can actually already be done, which is what your "return through" does: that `99` really is a `return 99 from enclosing`. It be hard to make explicit syntax for this, because if you do:

```
myhof():
    if c: return 99 from enclosing
    other stuff
```

You are probably expecting that `return` to be returning from the lambda thats an arg to `myhof` (bypassing `other stuff`), but actually it would just.. return from the `if` body! Because of course in Lobster the `if` body is also a lambda.. So you'd need `return 99 from enclosing of enclosing` ;)

@J0eCool who mentioned this problem before.

**Comment by aardappel** [comment]
Actually that one option mentioned in the TODO might be worth it: annotate the body call that it can't be returned out of. That would compile time error on any return past it. It could still allow `return from program` for any fatal errors.

**Comment by jcorbin** [comment]
Indeed, getting `defer` right can be difficult; e.g. in Go only the latest (about to be released) 1.14 is able to make them "as good as free" ( by compiler support for inlining them when possible and other prior work to avoid heap allocating a closure when possible )

**Comment by maddanio** [comment]
Why not destructors? I.e. simply a method called when something goes out of scope/ref count reaches 0? In my mind its a rather simple addition, but i fear i may be wrong? defer could then be trivially implemented

**Comment by aardappel** [comment]
@maddanio how would you define a destructor for the above `def translate` example (in my TODO ref) ?

**Comment by maddanio** [comment]
Pk, you are right. That would be a defer. Destructors would be connected to ref counting and called when it reaches 0

**Comment by maddanio** [comment]
Why do you think defer is expensive though? Its just code that gets called on scope exit. Since you don't have exceptions this is fully static, no? I.e. only paid for if used

**Comment by aardappel** [comment]
I have non-local returns, which have some of the same complexities as exceptions, see the top posts.

Defer would not be super expensive, but it is also not super useful since in the current code its not even that obvious when you should use them. Any function call may cause a non-local return, which means knowing which ones you should use defer for is hard.
